baseURL = 'https://viyaatagro.com/'
languageCode = 'en-us'
publishDir = 'docs'

theme = 'graysx'
title = 'Viyaat Agro'

## Site Settings
[params]
logo = "assets/img/logo.png"
favicon = "assets/favicon.png"

# Info
address = "No.93, 2nd Main, KSRTC Layout, Chikkalsandra, Uttarahalli Main Road, Subramanyapura, Bangalore, South Bangalore, Karnataka 560061"
email = "contact@viyaat.com"
phone = "7204062021"

# Socials

twitter = "#"
facebook = "#"
github = "https://github.com/Viyaat-Agro"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#contact"
  weight = 3
